// attendanceRequestActionTypes.js
export const CREATE_ATTENDANCE_REQUEST = 'CREATE_ATTENDANCE_REQUEST';
export const CREATE_ATTENDANCE_REQUEST_SUCCESS = 'CREATE_ATTENDANCE_REQUEST_SUCCESS';
export const CREATE_ATTENDANCE_REQUEST_FAILURE = 'CREATE_ATTENDANCE_REQUEST_FAILURE';


// attendanceRequestApprovalActionTypes.js
export const FETCH_ATTENDANCE_REQUEST_APPROVALS = 'FETCH_ATTENDANCE_REQUEST_APPROVALS';
export const FETCH_ATTENDANCE_REQUEST_APPROVALS_SUCCESS = 'FETCH_ATTENDANCE_REQUEST_APPROVALS_SUCCESS';
export const FETCH_ATTENDANCE_REQUEST_APPROVALS_FAILURE = 'FETCH_ATTENDANCE_REQUEST_APPROVALS_FAILURE';



// attendanceRequestApprovalActionTypes.js

export const UPDATE_ATTENDANCE_REQUEST_APPROVAL_REQUEST = 'UPDATE_ATTENDANCE_REQUEST_APPROVAL_REQUEST';
export const UPDATE_ATTENDANCE_REQUEST_APPROVAL_SUCCESS = 'UPDATE_ATTENDANCE_REQUEST_APPROVAL_SUCCESS';
export const UPDATE_ATTENDANCE_REQUEST_APPROVAL_FAILURE = 'UPDATE_ATTENDANCE_REQUEST_APPROVAL_FAILURE';


// attendanceRequestApprovalConstants.js
export const RESET_SUCCESS = 'RESET_SUCCESS';
