export const GET_ATTENDANCE_TIMES_REQUEST = 'GET_ATTENDANCE_TIMES_REQUEST';
export const GET_ATTENDANCE_TIMES_SUCCESS = 'GET_ATTENDANCE_TIMES_SUCCESS';
export const GET_ATTENDANCE_TIMES_FAILURE = 'GET_ATTENDANCE_TIMES_FAILURE';



export const MARK_ATTENDANCE_REQUEST = 'MARK_ATTENDANCE_REQUEST';
export const MARK_ATTENDANCE_SUCCESS = 'MARK_ATTENDANCE_SUCCESS';
export const MARK_ATTENDANCE_FAILURE = 'MARK_ATTENDANCE_FAILURE';


// attendanceConstants.js

export const FETCH_PRESENT_DATES_REQUEST = 'FETCH_PRESENT_DATES_REQUEST';
export const FETCH_PRESENT_DATES_SUCCESS = 'FETCH_PRESENT_DATES_SUCCESS';
export const FETCH_PRESENT_DATES_FAILURE = 'FETCH_PRESENT_DATES_FAILURE';



// actionTypes.js
export const FETCH_EMPLOYEE_ATTENDANCE_REQUEST = "FETCH_EMPLOYEE_ATTENDANCE_REQUEST";
export const FETCH_EMPLOYEE_ATTENDANCE_SUCCESS = "FETCH_EMPLOYEE_ATTENDANCE_SUCCESS";
export const FETCH_EMPLOYEE_ATTENDANCE_FAILURE = "FETCH_EMPLOYEE_ATTENDANCE_FAILURE";

