export const FETCH_EMPLOYEES_UNDER_MANAGER_REQUEST = 'FETCH_EMPLOYEES_UNDER_MANAGER_REQUEST';
export const FETCH_EMPLOYEES_UNDER_MANAGER_SUCCESS = 'FETCH_EMPLOYEES_UNDER_MANAGER_SUCCESS';
export const FETCH_EMPLOYEES_UNDER_MANAGER_FAILURE = 'FETCH_EMPLOYEES_UNDER_MANAGER_FAILURE';

// employeeConstants.js

export const GET_ACTIVE_EMPLOYEES_REQUEST = 'GET_ACTIVE_EMPLOYEES_REQUEST';
export const GET_ACTIVE_EMPLOYEES_SUCCESS = 'GET_ACTIVE_EMPLOYEES_SUCCESS';
export const GET_ACTIVE_EMPLOYEES_FAILURE = 'GET_ACTIVE_EMPLOYEES_FAILURE';


export const GET_ACTIVE_EMPLOYEES_DATA_REQUEST = 'GET_ACTIVE_EMPLOYEES_DATA_REQUEST';
export const GET_ACTIVE_EMPLOYEES_DATA_SUCCESS = 'GET_ACTIVE_EMPLOYEES_DATA_SUCCESS';
export const GET_ACTIVE_EMPLOYEES_DATA_FAILURE = 'GET_ACTIVE_EMPLOYEES_DATA_FAILURE';

