// Create Experience
export const CREATE_EXPERIENCE_REQUEST = "CREATE_EXPERIENCE_REQUEST";
export const CREATE_EXPERIENCE_SUCCESS = "CREATE_EXPERIENCE_SUCCESS";
export const CREATE_EXPERIENCE_FAIL = "CREATE_EXPERIENCE_FAIL";

// Fetch All Experiences
export const FETCH_ALL_EXPERIENCES_REQUEST = "FETCH_ALL_EXPERIENCES_REQUEST";
export const FETCH_ALL_EXPERIENCES_SUCCESS = "FETCH_ALL_EXPERIENCES_SUCCESS";
export const FETCH_ALL_EXPERIENCES_FAIL = "FETCH_ALL_EXPERIENCES_FAIL";

// Fetch Single Experience
export const FETCH_EXPERIENCE_REQUEST = "FETCH_EXPERIENCE_REQUEST";
export const FETCH_EXPERIENCE_SUCCESS = "FETCH_EXPERIENCE_SUCCESS";
export const FETCH_EXPERIENCE_FAIL = "FETCH_EXPERIENCE_FAIL";

// Update Experience
export const UPDATE_EXPERIENCE_REQUEST = "UPDATE_EXPERIENCE_REQUEST";
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS";
export const UPDATE_EXPERIENCE_FAIL = "UPDATE_EXPERIENCE_FAIL";

// Delete Experience
export const DELETE_EXPERIENCE_REQUEST = "DELETE_EXPERIENCE_REQUEST";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAIL = "DELETE_EXPERIENCE_FAIL";
