// actionTypes.js
export const FETCH_LEAVE_REQUESTS_REQUEST = 'FETCH_LEAVE_REQUESTS_REQUEST';
export const FETCH_LEAVE_REQUESTS_SUCCESS = 'FETCH_LEAVE_REQUESTS_SUCCESS';
export const FETCH_LEAVE_REQUESTS_FAILURE = 'FETCH_LEAVE_REQUESTS_FAILURE';


export const APPLY_LEAVE_REQUEST = 'APPLY_LEAVE_REQUEST';
export const APPLY_LEAVE_SUCCESS = 'APPLY_LEAVE_SUCCESS';
export const APPLY_LEAVE_FAILURE = 'APPLY_LEAVE_FAILURE';

export const APPROVE_LEAVE_REQUEST = 'APPROVE_LEAVE_REQUEST';
export const APPROVE_LEAVE_SUCCESS = 'APPROVE_LEAVE_SUCCESS';
export const APPROVE_LEAVE_FAILURE = 'APPROVE_LEAVE_FAILURE';


export const FETCH_LEAVE_DETAILS_REQUEST = 'FETCH_LEAVE_DETAILS_REQUEST';
export const FETCH_LEAVE_DETAILS_REQUEST_SUCCESS = 'FETCH_LEAVE_DETAILS_REQUEST_SUCCESS';
export const FETCH_LEAVE_DETAILS_REQUEST_FAILURE = 'FETCH_LEAVE_DETAILS_REQUEST_FAILURE';

// Rest of the action creators remain the same
